#!/bin/bash


# Decrypt server.key. Used for JWT authorization.
echo "Decrypting certificate." &&
openssl aes-256-cbc -d -md sha512 -pass pass:$CERT_KEY -in $HOME/assets/server.key.enc -out $HOME/assets/server.key -d &&

# Authenticate 
echo "Authorizing admin connection with org as '$SFDX_ADMIN_USERNAME'." &&
sfdx force:auth:jwt:grant --clientid $SFDC_WORKBENCH_APP_CLIENT_ID --jwtkeyfile $HOME/assets/server.key -u $SFDX_ADMIN_USERNAME --setalias sfdx-org-admin &&

# Remove server.key
echo "Removing certificate."
rm server.key &&

echo "Printing orgs."
sfdx force:org:list 